/* CyberDork OSINT Suite v7.0 - 700+ File Extension Database (auto-generated) */
const EXTENSION_CATEGORIES = {
  "🖼️ Images & Graphics": ["jpg", "jpeg", "png", "gif", "bmp", "svg", "webp", "tiff", "tif", "ico", "psd", "ai", "eps", "raw", "cr2", "nef", "orf", "sr2", "heic", "heif", "avif", "ind", "indd", "jp2", "jpx", "j2k", "wdp", "hdp", "dng", "arw", "rw2", "pef", "raf", "3fr", "dcr", "k25", "kdc", "mrw", "nrw", "ptx", "r3d", "rwl", "x3f", "cdr", "cgm", "dxf", "emf", "wmf", "art", "blp", "dds", "dib", "djvu", "exr", "gbr", "xcf", "pbm", "pgm", "ppm", "pnm", "pcx", "pict", "psb", "pdd", "psp", "jxl", "qoi", "fpx", "lbm", "egt", "fal", "svgz", "avs", "drw", "fits", "fff", "iiq", "mos", "mef", "bw", "sgi", "rwz", "srf", "cap", "tga", "icb", "vda", "vst", "hdr", "rgb", "rgba", "it8", "cvx"],
  "📄 Documents, Text & Email": ["pdf", "doc", "docx", "txt", "rtf", "odt", "ott", "oth", "odm", "pages", "xps", "oxps", "tex", "wpd", "wps", "abt", "ans", "asc", "ascii", "bib", "charset", "dtp", "epub", "gdoc", "mobi", "azw3", "chm", "lit", "fb2", "log", "msg", "rst", "sdw", "stw", "sxw", "info", "me", "1st", "sub", "man", "nfo", "pod", "markdown", "md", "text", "fdx", "fountain", "mcm", "pda", "ps", "sam", "fdb", "vce", "note", "tdf", "abw", "docm", "dot", "dotx", "dotm", "wri", "uot", "fodt", "odf", "odc", "odb", "odi", "odg", "otp", "ots", "stc", "std", "sda", "sdd", "vor", "kwd", "zabw", "aw", "xbd", "hwp", "hwt", "602", "rtfd", "keynote", "numbers", "cwk", "scriv", "pandoc", "gslides", "gsheet", "syn", "btd", "ltr", "eml", "pst", "ost", "mbox", "vcf", "vcard", "oft", "olm", "winmail.dat", "ice", "mbx", "nsf", "ics", "vcs", "email", "emlx", "mail", "archive", "dbx", "idx", "nmc", "olk15", "olk14", "olk", "olkmsg", "pab", "msp", "nap", "dat", "csv", "xls"],
  "📊 Spreadsheets & Data": ["xls", "xlsx", "xlsm", "xlsb", "xltx", "xltm", "csv", "tsv", "ods", "ots", "numbers", "sdc", "stc", "sxc", "wk1", "wk3", "wk4", "wks", "wq1", "wq2", "xlw", "xlr", "dbf", "dif", "slk", "gsheet", "fcs", "gnumeric", "qpw", "123", "xls3", "xls4", "xls5", "xlm", "xlt", "mpx", "et", "ett", "ettx", "parquet", "orc", "avro", "arrow", "feather", "dta", "sav", "por", "sas7bdat", "xpt", "rdata", "rds", "mat", "npy", "npz", "h5", "hdf5", "hdf", "nc", "fit", "edf", "jsonl", "ndjson", "uos", "uosx", "pmd", "wk2", "wrk", "xlk"],
  "🖥️ Presentations": ["ppt", "pptx", "pptm", "pps", "ppsx", "ppsm", "pot", "potx", "potm", "odp", "otp", "gslides", "key", "sdd", "sti", "sxi", "pez", "sow", "prz", "shw", "dpa", "dpg", "odg", "opd", "ppdf", "pdf", "sda", "vor", "kpr", "kpt", "fop", "fodp", "sxd", "otg", "oth"],
  "🎥 Video & Media": ["mp4", "mkv", "avi", "mov", "wmv", "flv", "webm", "m4v", "mpg", "mpeg", "3gp", "3g2", "vob", "ogv", "m2ts", "mts", "ts", "asf", "rm", "rmvb", "divx", "xvid", "f4v", "f4p", "f4a", "f4b", "roq", "svi", "mxf", "nsv", "drc", "gifv", "m1v", "m2v", "mpv", "dv", "wtv", "mod", "tod", "m4s", "m3u8", "m3u", "pls", "mpg2", "mp2v", "vp8", "vp9", "av1", "h264", "h265", "hevc", "mk3d", "mka", "mks", "ssa", "ass", "srt", "vtt", "sup", "idx", "sub", "mlv", "cpi", "qt", "ram", "wvx", "wma", "wax", "3gpp", "mpe"],
  "🎵 Audio & Sound": ["mp3", "wav", "aac", "flac", "ogg", "wma", "m4a", "alac", "aiff", "pcm", "opus", "amr", "mid", "midi", "ra", "ram", "au", "3ga", "ac3", "caf", "dts", "m4b", "m4p", "oga", "voc", "wv", "weba", "cda", "gsm", "mka", "tak", "ape", "mod", "s3m", "xm", "it", "mtm", "nsf", "spc", "ay", "gym", "vgm", "sid", "snd", "8svx", "w64", "wve", "spx", "mp2", "mp1", "mpa", "mpc", "ofr", "wax", "adt", "adts", "asd", "mp4a", "aax", "m4r"],
  "📦 Archives & Compressed": ["zip", "rar", "7z", "tar", "gz", "bz2", "xz", "iso", "cab", "lz", "lzma", "lzh", "arj", "z", "ace", "apk", "tgz", "tbz2", "tlz", "txz", "zipx", "sit", "sitx", "sea", "shar", "mar", "pax", "war", "ear", "sar", "phar", "cpio", "rpm", "deb", "zst", "lz4", "br", "arc", "ar", "paq", "paq8", "rk", "jar", "pak", "hqx", "uu", "bz", "tbz", "ta.gz", "taz", "wim", "esd", "swm", "vhd", "vhdx", "vmdk", "vdi", "qcow2", "ova", "ovf", "sfs", "sqfs", "img", "nrg", "mdf", "mds", "ccd", "cue", "bin"],
  "⚙️ Executable & Systems": ["exe", "msi", "bat", "cmd", "sh", "bin", "app", "dmg", "deb", "rpm", "jar", "gadget", "com", "vbs", "ps1", "wsf", "scr", "drv", "sys", "dll", "so", "dylib", "cpl", "inf", "reg", "icns", "elf", "cgi", "pl", "run", "out", "aab", "lnk", "msix", "msixbundle", "appx", "appxbundle", "xpi", "crx", "swf", "class", "coff", "o", "obj", "lib", "a", "la", "lo", "ko", "module", "efi", "apk", "ipa", "apks", "xapk", "pif", "application", "msu", "msp", "mst", "isu", "job", "vsix", "appinstaller"],
  "🌐 Web & Code": ["html", "htm", "css", "js", "ts", "json", "xml", "php", "py", "java", "c", "cpp", "cs", "rb", "go", "swift", "kt", "sql", "asp", "aspx", "jsp", "xhtml", "vue", "jsx", "tsx", "less", "scss", "sass", "yaml", "yml", "ini", "env", "config", "ejs", "pug", "twig", "hbs", "blade", "erb", "rhtml", "jade", "coffee", "ls", "rs", "clj", "cljs", "hs", "ml", "m", "lua", "r", "scala", "pl", "pm", "tcl", "awk", "sed", "bat", "ipynb", "toml", "dockerfile", "makefile", "cmake", "mjs", "cjs", "mts", "cts", "dart", "f", "fs", "fsx", "ex", "exs", "erl", "hrl", "elm", "groovy", "gradle", "kts", "nim", "odin", "zig", "v", "h", "hpp", "hxx", "hh", "csproj", "sln", "vbproj", "sh", "zsh", "bash", "fish", "psm1", "psd1", "conf", "cfg", "properties", "lock", "map", "wasm", "wat", "proto", "graphql", "gql", "apib", "raml", "openapi", "swagger", "postman", "har", "wsdl", "wadl", "xsd", "dtd", "rss", "atom", "sitemap", "webmanifest", "htaccess", "htpasswd", "editorconfig", "gitignore", "gitattributes", "npmrc", "yarnrc", "babelrc", "eslintrc", "prettierrc"],
  "🗄️ Database Files": ["db", "sqlite", "sqlite3", "mdb", "accdb", "sql", "sdf", "sqlitedb", "dbf", "myd", "myi", "ibd", "fdb", "gdb", "pdb", "dbs", "db3", "sqlite2", "ldb", "ndf", "mdf", "ldf", "bak", "ckp", "dat", "dta", "xdb", "frm", "opt", "trg", "ibz", "mrg", "trn", "tlg", "db2", "sdb", "tbl", "tmd", "vdb", "dx", "adf", "geo", "txt", "tsv", "csv"],
  "📐 CAD & 3D Design": ["dwg", "dxf", "stl", "obj", "fbx", "3ds", "blend", "dae", "ply", "iges", "step", "stp", "max", "ma", "mb", "skp", "c4d", "lwo", "3dm", "f3d", "sldprt", "sldasm", "prt", "part", "gltf", "glb", "usdz", "igs", "jt", "x_t", "x_b", "sat", "sab", "catpart", "catproduct", "ipt", "iam", "asm", "dwf", "dwfx", "dwt", "dxb", "rvt", "rfa", "3mf", "amf", "vrml", "wrl", "x3d", "pov", "asc", "scad", "fcstd", "fcstd1", "fem", "kml", "kmz"],
  "🔤 Fonts & Typography": ["ttf", "otf", "woff", "woff2", "eot", "fon", "fnt", "pfb", "pfm", "afm", "ttc", "dfont", "suit", "cff", "gsf", "tef", "gai", "pfa", "otc", "ps", "vfb", "ufo", "sfd", "bdf", "pcf", "psf", "gra", "pfr"],
  "🔐 Security & Crypto": ["crt", "cer", "pem", "der", "pfx", "p12", "csr", "gpg", "pgp", "key", "asc", "ovpn", "crl", "jks", "keystore", "bks", "p7b", "p7c", "spc", "sst", "pvk", "skr", "gnupg", "sec", "pub", "sig", "ring", "krb", "kdb", "kdbx", "kwallet", "wallet", "vault", "age", "yubikey", "totp", "hotp", "seed", "mnemonic", "enc", "aes", "rsa", "dsa", "ecdsa", "jwt", "jwk", "jwks", "md5", "sha1", "sha256", "hash"],
  "🎮 Game Files": ["pak", "vpk", "gam", "sav", "rom", "nes", "sfc", "gba", "gbc", "nds", "bin", "cue", "n64", "z64", "v64", "gcm", "wbfs", "cso", "iso", "chd", "mdf", "mds", "ccd", "toc", "gb", "3ds", "cia", "3dsx", "dsi", "smc", "fig", "srm", "state", "sps", "pst", "wad", "bup", "rev", "dol", "el", "szs", "szp", "arc", "lz", "yaz0", "brres", "brsar", "rarc", "u8", "bms", "bsa", "esp", "esm", "mod", "pk3", "pk4", "iwd", "bik", "wot", "gpf", "xbe", "xex", "sln", "elf", "pkg", "pud"],
  "🔬 Scientific, Data & Logs": ["dat", "fit", "hdf", "hdf5", "nc", "mat", "rdata", "rds", "csv", "parquet", "avro", "orc", "npy", "npz", "wav", "bin", "pdb", "cif", "mol", "sdf", "sd", "smiles", "pse", "xyz", "gms", "mcif", "fasta", "fastq", "gb", "genbank", "sam", "bam", "vcf", "bed", "gff", "gtf", "kml", "kmz", "shp", "geojson", "topojson", "gpx", "dbf", "prj", "sbx", "sbn", "cpg", "mif", "tab", "log", "dmp", "crash", "dump", "err", "out", "syslog", "journal", "events", "txt", "asc", "trace", "diag", "evtx", "evt", "etl", "blg", "perflog", "wprp", "psess"]
};

const EXTENSION_TOTAL = 937;
